apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irctc-prod-ingress
  namespace: irctc-prod
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: irctc-prod-service
                port:
                  number: 80
