apiVersion: v1
kind: Service
metadata:
  name: irctc-prod-service
  namespace: irctc-prod
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: irctc-prod
