name: irctc-prod ## $Project Name / $Branch

on:
  push:
    branches:
      - main ## CHANGE Branch Name HERE !!!

permissions:
  id-token: write  ## NEEDED!!!
  contents: read

jobs:
  credentials_build_deploy:
    name: Building and Pushing the Image
    runs-on: [ubuntu-latest] ## private/public runner

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::204998944520:role/GitHubActionRole  # change AWS account HERE
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2      

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY:  ${{ steps.login-ecr.outputs.registry }}         
        ECR_REPOSITORY: eks-repo  ## CHANGE ECR Name HERE!!!
      run: |
        IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
        ENV=prod                                   ## CHANGE Env Name HERE!!!
        BRANCH=${GITHUB_REF##*/}
        
        docker build -f Dockerfile-$ENV --build-arg ARG_ENV=${ENV} -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG
        echo $IMAGE_TAG
        cd manifest/prod                                                             ## CHANGE DIR Name HERE!!!
        sed -i "s|CHANGE-IMAGE-NAME|$ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG|g" deployment.yaml
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name eks-cluster
    - name: Deploy to EKS with Customization
      run: |
        kubectl config use-context arn:aws:eks:us-east-1:204998944520:cluster/eks-cluster
        kubectl apply -f manifest/prod/namespace.yaml
        kubectl apply -f manifest/prod/deployment.yaml
        kubectl apply -f manifest/prod/service.yaml
        kubectl apply -f manifest/prod/ingress.yaml
        kubectl get svc -n irctc-prod
